<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>Moonforged.BuildPieces</RootNamespace>
    <AssemblyName>MoonforgedBuildPieces</AssemblyName>
    <LangVersion>10</LangVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="NewFolder\**" />
    <EmbeddedResource Remove="NewFolder\**" />
    <None Remove="NewFolder\**" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="mbp_windows" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="mbp_windows" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="assembly_valheim">
      <HintPath>Libs\assembly_valheim.dll</HintPath>
    </Reference>
    <Reference Include="BepInEx">
      <HintPath>Libs\BepInEx.dll</HintPath>
    </Reference>
    <Reference Include="Jotunn">
      <HintPath>Libs\Jotunn.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>Libs\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AssetBundleModule">
      <HintPath>Libs\UnityEngine.AssetBundleModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>Libs\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ParticleSystemModule">
      <HintPath>Libs\UnityEngine.ParticleSystemModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>Libs\UnityEngine.PhysicsModule.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
